// Code generated by microgen 0.9.0. DO NOT EDIT.

package service

import service "github.com/dreamsxin/go-kitcli/examples/addsvc/addsvc"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
